In [1]:
import numpy as np

In [2]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [3]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [4]:
10 * np.ones((2,3))

array([[10., 10., 10.],
       [10., 10., 10.]])

In [5]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [8]:
np.random.random()

0.7438191675806511

In [9]:
np.random.random((2,3))

array([[0.64099929, 0.81693938, 0.8665181 ],
       [0.75523899, 0.8609166 , 0.74099609]])

In [10]:
np.random.randn(2,3)

array([[-1.28624799,  0.5156374 ,  1.00965345],
       [-0.40246441,  0.99368213,  0.49474933]])

In [2]:
A = np.random.randn(10000)

In [3]:
A.mean()

0.008169020958427274

In [4]:
np.mean(A)

0.008169020958427274

In [5]:
A.var()

1.0086746201917638

In [6]:
A.std()

1.0043279445438944

In [7]:
B = np.random.randn(10000, 3)

In [8]:
B.mean(axis=0)

array([-0.02171629, -0.00587425, -0.00271556])

In [11]:
B.mean(axis =1).shape

(10000,)

In [13]:
np.cov(B).shape

(10000, 10000)

In [14]:
np.cov(B.T)

array([[ 0.98327927,  0.00802939, -0.01122634],
       [ 0.00802939,  1.00369749,  0.00171739],
       [-0.01122634,  0.00171739,  0.99809475]])

In [15]:
np.cov(B, rowvar=False)

array([[ 0.98327927,  0.00802939, -0.01122634],
       [ 0.00802939,  1.00369749,  0.00171739],
       [-0.01122634,  0.00171739,  0.99809475]])

In [18]:
np.random.randint(0,10,size=(3,3))

array([[3, 4, 6],
       [4, 1, 8],
       [7, 1, 2]])

In [19]:
np.random.choice(10,size=(3,4))

array([[3, 5, 6, 7],
       [6, 8, 2, 0],
       [5, 0, 8, 0]])