In [2]:
import numpy as np

In [1]:
L = [[1,2],[3,4]]
L

[[1, 2], [3, 4]]

In [3]:
L[0]

[1, 2]

In [4]:
L[0][1]

2

In [8]:
A = np.array([[1,2],[3,4]])
A

array([[1, 2],
       [3, 4]])

In [9]:
A[0][1]

2

In [10]:
A[0,1]

2

In [12]:
A[:,0]

array([1, 3])

In [13]:
A.T

array([[1, 3],
       [2, 4]])

In [14]:
np.exp(A)

array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])

In [15]:
np.exp(L)

array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])

In [18]:
B = np.array([[1,2,3],[4,5,6]])
B

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
A.dot(B)

array([[ 9, 12, 15],
       [19, 26, 33]])

In [20]:
A.dot(B.T)

ValueError: shapes (2,2) and (3,2) not aligned: 2 (dim 1) != 3 (dim 0)

In [21]:
np.linalg.det(A)

-2.0000000000000004

In [22]:
np.linalg.inv(A)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [23]:
np.linalg.inv(A) .dot(A)

array([[1.00000000e+00, 0.00000000e+00],
       [1.11022302e-16, 1.00000000e+00]])

In [24]:
np.trace(A)

5

In [25]:
np.diag(A)

array([1, 4])

In [26]:
np.diag([1,4])

array([[1, 0],
       [0, 4]])

In [27]:
np.linalg.eig(A)

EigResult(eigenvalues=array([-0.37228132,  5.37228132]), eigenvectors=array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]]))

In [28]:
Lam, V = np.linalg.eig(A)

In [30]:
V[:,0] * Lam[0] , A @ V[:,0]

(array([ 0.30697009, -0.21062466]), array([ 0.30697009, -0.21062466]))

In [31]:
np.allclose(V[:,0] * Lam[0] , A @ V[:,0])

True

In [32]:
np.allclose(V @ np.diag(Lam), A @ V )

True

In [34]:
np.linalg.eigh
# for Symmetric Matrix.. Uses Hermitian Matrix.. can Handle Complex Numbers

<function eigh at 0x00000138241BDDB0>